analysis_config: ../GRCh37/.snappy_pipeline/config.yaml

dirs:
  root_dir: ../GRCh37
  raw_dir: raw_data/NA12878
  expected_dirs:
    - ngs_mapping
    - variant_calling
    - variant_export

pipeline_config:
  pipeline_step:
    name: ''
    version: 1

  $ref: 'file://../.snappy_pipeline/config.yaml'


