static_data_config:
  cosmic:
    path: /fast/projects/cubit/20.05/static_data/db/COSMIC/v72/GRCh37/CosmicAll.vcf.gz
  dbsnp:
    path: /fast/projects/cubit/20.05/static_data/db/dbSNP/b147/GRCh37/All_20160408.vcf.gz
  reference:
    path: /fast/projects/cubit/20.05/static_data/reference/GRCh37/hs37d5/hs37d5.fa
  clinvar:
    path: /fast/projects/cubit/20.05/static_data/db/ClinVar/20170530/GRCh37/clinvar_20170530.vcf.gz
  dbnsfp:
    path: /fast/projects/medgen_genomes/2017-03-17_cubi_pipeline_v2_grch37_and_38/GRCh37/variant_annotation/tracks/GRCh37/dbNSFP3.4a_variant.GRCh37.tsv.gz
  exac:
    path: /fast/projects/cubit/20.05/static_data/db/ExAC/GRCh37/release0.3.1/ExAC.r0.3.1.sites.vep.vcf.gz
  gnomad_exomes:
    path: /fast/projects/cubit/20.05/static_data/db/gnomAD/release2.0.2/GRCh37/gnomad.exomes.r2.0.2.sites.vcf.gz
  gnomad_genomes:
    path: /fast/projects/cubit/20.05/static_data/db/gnomAD/release2.0.2/GRCh37/gnomad.genomes.r2.0.2.sites.vcf.gz

step_config:
  ngs_mapping:
    tools:
      dna:
        - bwa
    bwa:
      path_index: /fast/projects/cubit/20.05/static_data/precomputed/BWA/0.7.17/GRCh37/hs37d5/hs37d5.fa
      num_threads_align: 16
    target_coverage_report:
      path_target_interval_list_mapping:
        - pattern: "Agilent SureSelect Human All Exon V6.*"
          name: "Agilent SureSelect Human All Exon V6 (S07604514)"
          path: /data/static/agilent-v6.bed

data_sets:
  mundlos_limb:
    sodar_uuid: 554d78d6-f1c6-4831-897e-2f871815c30c
    file: 2021_germline_use_case.tsv
    search_patterns:
      - {left: '*_R1.fastq.gz', right: '*_R2.fastq.gz'}
      - {left: '*_R1_*.fastq.gz', right: '*_R2_*.fastq.gz'}
    search_paths:
      - /data/raw_data
    type: germline_variants
    naming_scheme: only_secondary_id
